name: Scrape cinema times

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 7,10,13,16,19,21 * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

        with:
          ruby-version: "3.1"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Scrape curzon times
        run: bundle exec ruby scrapes/curzon.rb

      - name: Scrape prince charles times
        run: bundle exec ruby scrapes/princecharles.rb

      - name: Scrape metadata
        run: bundle exec ruby scrapes/metadata.rb

      - name: Commit results
        run: |
          git config --global user.name 'Russell Dunphy'
          git config --global user.email 'rsslldnphy@users.noreply.github.com'
          git add -A
          if ! git diff-index --quiet HEAD --; then
              git commit -am "Scrape results"
              git push
          fi 
